### ISSUE TITLE
Contributor Docs

### ISSUE THREAD

**Issue by patflynn** [transparency-dev/trillian-tessera#10]
Catch all to document the missing repo docs for contributors.  

Probably should include:

- [x] contributing.md
- [ ] security.md
- [ ] community.md
- [x] readme.md
- [ ] changelog.md
- [x] pointer to roadmap
- [ ] new issue template
- [ ] PR template

**Comment by roger2hk** [comment]
For security.md, is this repository covered by the [Google OSS VRP](https://bughunters.google.com/open-source-security)?

**Comment by roger2hk** [comment]
Created trillian-tessera@googlegroups.com for receiving security vulnerability report.

**Comment by tracymiranda** [comment]
I recommend we add a set of health files to the root .github folder so they can apply as default to all the repos under transparency-dev. The files would be:

- [ ] code of conduct
- [ ] issue template files
- [ ] pr template

**Comment by tracymiranda** [comment]
I can't fork the .github folder as it is empty

@patflynn could you pls add a readme.md (it can be empty) to https://github.com/transparency-dev/.github so I can create a pull request with the community health files.

**Comment by patflynn** [comment]
@tracymiranda  
https://github.com/transparency-dev/.github/pull/1
