### ISSUE TITLE
Conformance & Example Personalities

### ISSUE THREAD

**Issue by patflynn** [transparency-dev/trillian-tessera#8]
**Objective**

Provide Trillian Tessera personalities that:
1. allows to run conformance/compliance/performance tests, and
2. demonstrates how to correctly run and use the Trillian Tessera library by implementing the [tlog tiles API](https://github.com/C2SP/C2SP/blob/main/tlog-tiles.md) and a custom write endpoint, and supporting any officially provided storage implementation and plug-ins.

**Tasks**

- [x] Organize the existing example personalities into the correct directories.
- [x] POSIX conformance personality
- [x] MySQL conformance personality
- [x] GCP conformance personality
- [x] POSIX one-shot example personality

**Comment by roger2hk** [comment]
**Objective**

Provide Trillian Tessera personalities that:
1. allows to run conformance/compliance/performance tests, and
2. demonstrates how to correctly run and use the Trillian Tessera library by implementing the [tlog tiles API](https://github.com/C2SP/C2SP/blob/main/tlog-tiles.md) and a custom write endpoint, and supporting any officially provided storage implementation and plug-ins.
